eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: user-service
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/users/**
          - id: user-service-roles
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/roles/**
          - id: user-service-authentication
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/authentication/**
          - id: review-service
            uri: http://localhost:9090
            predicates:
              - Path=/api/v1/reviews/**